### ISSUE TITLE
Some issue regarding minification

### ISSUE THREAD

**Issue by cjuner** [VIISON/ShopwareStripePayment#11]
@mihaiplasoianu sent me some error logs from the Shopware backend I'll still have to check out.

**Comment by cjuner** [comment]
Should be fixed with https://github.com/VIISON/minimal-smartyness/commit/b0e8b04c7fa116e58ee6f1c62ed06890ff90d701 and https://github.com/VIISON/minimal-smartyness/commit/7984e4894095f95a1181553d8d62564eeb7d037d.

**Comment by svenmuennich** [comment]
The known workaround done in 83cdca7ecafe4575763f742d0e8e74b6cc964902 and @cjuner's fixes make the minification run without errors.
