### ISSUE TITLE
Plugin not Shopware < 5.2 compatible anymore

### ISSUE THREAD

**Issue by samuelvogel** [VIISON/ShopwareStripePayment#21]
It seems the `CSRFWhitelistAware` interface is required since version `2.0.0`: https://forum.shopware.com/discussion/45500/stripe-plugin-fehler-beim-checkout

**Comment by svenmuennich** [comment]
Well, the plugin works in Shopware 4 and [there is code in place](https://github.com/VIISON/ShopwareStripePayment/blob/88d5aee5f2b501e57a4f193daf0526046633140e/Controllers/Frontend/StripePayment.php#L2-L7) to ensure the `CSRFWhitelistAware` interface is defined. I think there was probably another reason for the error described.
