### ISSUE TITLE
Shopware 5.3 compatibility

### ISSUE THREAD

**Issue by mihaiplasoianu** [VIISON/ShopwareStripePayment#23]
With Shopware 5.3, the frontend fields for _credit card number_, _validity date_ and _cvc_ are missing.

Error is
```
shippingPayment:524 Uncaught ReferenceError: $ is not defined
    at shippingPayment:524
```
and occurs in https://github.com/VIISON/ShopwareStripePayment/blob/ffcf50b0ee788959cd86e6075fda236994228a1f/Views/responsive/frontend/checkout/shipping_payment.tpl#L23

**Comment by samuelvogel** [comment]
This might be related to async script loading changes in Shopware 5.3.
