### ISSUE TITLE
Cannot enter credit card infos in SW 4.3

### ISSUE THREAD

**Issue by windaishi** [VIISON/ShopwareStripePayment#24]
In SW 4.3 one cannot enter its credit card information in the checkout. The screenshot should explain the problem.
The field for Card number, CVC and valid to are missing. Maybe its a layout problem.

![image](https://user-images.githubusercontent.com/6232639/29139029-c6e1a8bc-7d45-11e7-86df-4c98763047d4.png)

**Comment by svenmuennich** [comment]
The payment form works in my vanilla Shopware 4.3 installation:

![image](https://user-images.githubusercontent.com/1932115/29159312-4d4bdbee-7dae-11e7-93ad-5322ec12b998.png)

Can you please double check that the template issues are not caused by a different plugin?

**Comment by windaishi** [comment]
Issue was "solved". Problem appears when the Plugin is symlinked. See "Shopware Development" in docs to see how to correctly modify your SW to properly support symlinks
