### ISSUE TITLE
Please use correct return type

### ISSUE THREAD

**Issue by aWuttig** [VIISON/ShopwareStripePayment#26]
https://github.com/VIISON/ShopwareStripePayment/blob/master/Util.php#L135

Corresponding to the PSR2 standard and several coding guidelines please add the correct return type here?

"The" ist not an class ;-)

**Comment by svenmuennich** [comment]
Good find! Looks like there are quite a few `@returns` and `@throws` missing their type hint. We'd appreciate if you could send us a pull request fixing this, if it bothers you and cannot wait 😉

**Comment by aWuttig** [comment]
I already make a fork of your plugin and call your company for further proceeding, because the plugin is based on "old" 5.1 structure and in the future it should be compat to the new 5.2 structure. I try to help as far as i can in this stuff.

**Comment by svenmuennich** [comment]
We must use the "old" structure, since this plugin is still compatible with all Shopware versions down to `4.3.x`.

**Comment by aWuttig** [comment]
Than we better have to make a legacy branch (2.x) for down to 4.3.x versions? In case of an bugfix you have to upload two versions in the shopware store which is a bit terrifying but neccessary. That is what are versions for ;-)

**Comment by svenmuennich** [comment]
Closed via 1268663784bd1cfa2a03d4fb90907c91cfac5347
