### ISSUE TITLE
Plugin not compatible to Shopware 5.5

### ISSUE THREAD

**Issue by svenmuennich** [VIISON/ShopwareStripePayment#32]
The plugin is currently not compatible to Shopware 5.5 because `Shopware\Models\Payment\Payment::setClass()` was removed, which breaks the installation.

**Comment by fixpunkt** [comment]
This was re-added: https://github.com/shopware/shopware/commit/4b1fd5a736e86a9d0421877e803f09d18da09d53

**Comment by fixpunkt** [comment]
@VIISON/sales would you mind giving the plugin a round of testing?

**Comment by antoniokupresak** [comment]
@fixpunkt Our testing instances only allows choosing the Shopware 5.5.0-BETA1 Tag, which does not include your above mentioned commit. 
I'm afraid that we have no practical possibility to test this.

**Comment by fixpunkt** [comment]
@niklasbuechner can we provide nightly-master Shopware images for pickware.io?

**Comment by niklasbuechner** [comment]
Sure, I will set up the system. The first build is running right now.

**Comment by niklasbuechner** [comment]
@fixpunkt @antoniokupresak Shopware 5.5 nightlys are not available on pickware.io.

**Comment by antoniokupresak** [comment]
I've successfully tested that the checkout process using a credit cards is working in the SW 5.5 nightly build with the current master of the stripe plugin. 

Is that sufficient already? @fixpunkt @svenmuennich

**Comment by fixpunkt** [comment]
Yup, that should be sufficient. Thank you very much!
