### ISSUE TITLE
Use {$smarty.block.parent} instead of append

### ISSUE THREAD

**Issue by PidaPan** [VIISON/ShopwareStripePayment#35]
In order to support better extensibility for other themes or plugins the `append`/`prepend` keywords in smarty blocks should no longer be used. SW recommends using `{$smarty.block.parent}` to reference the parent content of the block.

Cite from SW docs ([here](https://developers.shopware.com/designers-guide/getting-started/#template-blocks)):

> Attention: It is recommended to not use the smarty block parameter append and prepend, so other templates or plugins can overwrite the same block without problems.

**Comment by akleiber** [comment]
the fact that you use `append` and `prepend` blocks other plugins from extending the corresponding smarty blocks - can you please update your plugin according to shopware recommendations?

**Comment by svenmuennich** [comment]
We're quite busy at the moment. Would you mind opening a pull request with the necessary fixes?
