### ISSUE TITLE
Update Stripe manual regarding new PaymentIntents API (PSD2)

### ISSUE THREAD

**Issue by jessicapleier** [VIISON/ShopwareStripePayment#52]
https://stripe.com/de/guides/strong-customer-authentication

**Comment by jessicapleier** [comment]
I've already added this information in the WIP version of the new documentation, which can be reviewed here @antoniokupresak 
https://docs.google.com/document/d/1musYvgVjdTxRpcBzNPLSmJLeGIoYaiIXSW__iIVHiyo/edit#heading=h.6mrihfrt1uxt

**Comment by antoniokupresak** [comment]
I added my feedback to the document.

**Comment by jessicapleier** [comment]
https://docs.google.com/document/d/1FfZU0AqEWtiXd7Ito6e7UiLzfpP5F_D8CT9gtogaZlk/edit#heading=h.6mrihfrt1uxt
