### ISSUE TITLE
Support for webhook payment_intent.succeeded

### ISSUE THREAD

**Issue by nullsub** [VIISON/ShopwareStripePayment#53]
Are there any plans to support the payment_intent webhooks, such as payment_intent.succeeded?

**Comment by svenmuennich** [comment]
Can you please elaborate? Do you mean as an alternative to waiting for the redirect?

**Comment by nullsub** [comment]
> Do you mean as an alternative to waiting for the redirect?

Yes. In my case redirect is not used and the webhook needs to be evaluated. 

Just like `processChargeSucceededEvent`   + setting the transactionId in the order should do it I think.

**Comment by nullsub** [comment]
I changed my flow to use the redirect. So it is no longer a priority for me.
Thank you
